#!/usr/bin/env bash

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"

cd "$repo_root"

echo "Running dotnet format..."
dotnet format Vortex.sln --verify-no-changes

echo "Running dotnet build..."
dotnet build Vortex.sln
